// <auto-generated />
using IdentityServerAspNetIdentity.Data.Migrations.TenantManagement;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IdentityServerAspNetIdentity.Migrations
{
    [DbContext(typeof(TenantManagementDbContext))]
    partial class TenantManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IdentityServerAspNetIdentity.Data.Migrations.TenantManagement.ExternalAuthenticatingScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExternalAuthenticatingScheme");
                });

            modelBuilder.Entity("IdentityServerAspNetIdentity.Data.Migrations.TenantManagement.TenantAuthenticatingScheme", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "SchemeId");

                    b.HasIndex("SchemeId");

                    b.ToTable("TenantAuthenticatingScheme");
                });

            modelBuilder.Entity("IdentityServerAspNetIdentity.Data.Migrations.TenantManagement.TenantInfo", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId");

                    b.ToTable("TenantInfo");
                });

            modelBuilder.Entity("IdentityServerAspNetIdentity.Data.Migrations.TenantManagement.TenantAuthenticatingScheme", b =>
                {
                    b.HasOne("IdentityServerAspNetIdentity.Data.Migrations.TenantManagement.ExternalAuthenticatingScheme", "ExternalAuthenticatingScheme")
                        .WithMany("TenantAuthenticatingSchemes")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdentityServerAspNetIdentity.Data.Migrations.TenantManagement.TenantInfo", "TenantInfo")
                        .WithMany("TenantAuthenticatingSchemes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
